# Generated by Django 4.1.1 on 2022-10-01 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_image', models.ImageField(blank=True, null=True, upload_to='userProfileImgs/')),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('NA', 'NA')], default='NA', max_length=45)),
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('auth_token', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('github', models.URLField(blank=True, default='', null=True)),
                ('linkdin', models.URLField(blank=True, default='', null=True)),
                ('twitter', models.URLField(blank=True, default='', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userlinks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
