# Generated by Django 4.1.1 on 2022-10-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='books_issued',
            field=models.IntegerField(default=0),
        ),
    ]
