# Generated by Django 4.1.1 on 2022-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_userprofiles_books_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='books_issued',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
