# Generated by Django 4.1.1 on 2022-11-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_alter_userprofiles_books_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='userQr/'),
        ),
    ]
