# Generated by Django 4.1.1 on 2022-10-01 17:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('createdOn', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100, null=True)),
                ('book_desc', models.CharField(max_length=150, null=True)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='bookImage/')),
                ('book_author', models.CharField(max_length=100, null=True)),
                ('book_publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book_quantity', models.IntegerField(default=0)),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='book.bookcategory')),
            ],
        ),
    ]
