# Generated by Django 4.1.1 on 2022-10-01 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_rename_books_book_bookloandetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookLoanDetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
