# Generated by Django 4.1.1 on 2022-10-01 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0003_alter_bookloandetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookLoanDetail', to='book.book'),
        ),
        migrations.AlterField(
            model_name='bookloandetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookLoanDetail', to=settings.AUTH_USER_MODEL),
        ),
    ]
