# Generated by Django 4.1.1 on 2022-10-01 19:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_bookfinepaydetail_bookfine'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reervation_date', models.DateField(default=datetime.date.today)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookReservation', to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookReservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
