# Generated by Django 4.1.1 on 2022-10-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_rename_reervation_date_bookreservation_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about_book',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
