# Generated by Django 4.1.1 on 2022-10-02 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_about_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloandetail',
            name='estimated_return_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bookloandetail',
            name='return_status',
            field=models.CharField(choices=[('returned', 'returned'), ('rending', 'pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookloandetail',
            name='return_date',
            field=models.DateField(default=None),
        ),
    ]
