# Generated by Django 4.1.1 on 2022-10-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookloandetail_estimated_return_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
