# Generated by Django 4.1.1 on 2022-10-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_book_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='return_status',
            field=models.CharField(choices=[('returned', 'returned'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
