# Generated by Django 4.1.1 on 2022-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_bookloandetail_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='return_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
