# Generated by Django 4.1.1 on 2022-10-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_bookloandetail_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='return_status',
            field=models.CharField(choices=[('pending', 'pending'), ('returned', 'returned')], default='pending', max_length=10),
        ),
    ]
