# Generated by Django 4.1.1 on 2022-10-02 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_bookloandetail_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookLoanDetail', to='book.book'),
        ),
    ]
