# Generated by Django 4.1.1 on 2022-10-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_alter_bookloandetail_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='return_date',
            field=models.DateField(default='<jamming-date>', null=True),
        ),
    ]
