# Generated by Django 4.1.1 on 2022-10-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_bookloandetail_estimated_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_barcode',
            field=models.ImageField(blank=True, null=True, upload_to='bookBarcode/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_isbn',
            field=models.CharField(max_length=13, null=True, verbose_name='ISBN'),
        ),
    ]
