# Generated by Django 4.1.1 on 2022-10-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_bookloandetail_estimated_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloandetail',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
