# Generated by Django 4.1.1 on 2022-10-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_bookloandetail_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreservation',
            name='return_status',
            field=models.CharField(choices=[('reserved', 'reserved'), ('alloted', 'alloted')], default='reserved', max_length=10),
        ),
    ]
