# Generated by Django 4.1.1 on 2022-10-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_bookreservation_return_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreservation',
            old_name='return_status',
            new_name='reservation_status',
        ),
    ]
